// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crudDotnet.Models;

namespace crudDotnet.Migrations
{
    [DbContext(typeof(FilmeContext))]
    [Migration("20200508172720_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("crudDotnet.Models.Filme", b =>
                {
                    b.Property<int>("FilmeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FilmeAnoLancamento");

                    b.Property<double>("FilmeImdb");

                    b.Property<string>("FilmeNome");

                    b.Property<string>("FilmeSinopse");

                    b.Property<string>("FilmeUrlImg");

                    b.HasKey("FilmeId");

                    b.ToTable("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
